---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: multiarch-publish-dev

- name: publish
  pull: never
  image: spritsail/docker-publish
  settings:
    repo: spritsail/docker-multiarch-publish
    from: multiarch-publish-dev
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
  when:
    branch:
    - master
    event:
    - push
